# Generated by Django 4.1.12 on 2024-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('mdate', models.DateField()),
            ],
        ),
    ]
